### ISSUE TITLE
Peer to peer accessibilty

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/Portfolio#12]

**Comment by JustoRago** [comment]
The only thing I have to say is that you do not require a span element inside your buttons to contain the text, and that not having it may be better to make sure the text fits perfectly inside them, as well as requiring less classes to style.

**Comment by PedroH-Neves** [comment]
Your code is really great 💯 👍 
I only have some suggestions as: 

- when someone click in the media icons to open in a new tab
- when clicking on the menu in portfolio, about or contact to lead to the section
- in the inputs you can use labels even if they are with no text with just classe to have a better accessibility

Good luck with your project 😁

**Comment by KanzaTahreem** [comment]
You have done a great job with the code. Keep it up 💪💯
However, there's always room for improvement. 
- I think it would be better if you try adding alt-attribute for icons.

Happy Coding!.💻💡

**Comment by Miliyonayalew** [comment]
Thanks, guys. It's valuable feedback
