### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/Portfolio#15]
## Please put your feedback here

**Comment by didierganthier** [comment]
- [ ] Popup should take the height of the screen without scrolling for a better User Experience

**Comment by cvalencia1991** [comment]
you are doing a good job for coding, you should do the next changes:

- try to fix the GitHub image in the section of the main 
- the validation form should the boxes when it's incorrect filling the form, should the border be red

**Comment by OscarFMdev** [comment]
**Your portfolio is looking great!** However I noticed that: 

- [ ] The pop up background for desktop version could be gray so it highlights the pop-up window

**Comment by Miliyonayalew** [comment]
Thank you for your valuable feedback💡 🎯 .
