### ISSUE TITLE
Portfolio application deploy

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/Portfolio#9]
[Live Demo Link](https://miliyonayalew.github.io/Portfolio/)

**Comment by Qoosim** [comment]
# *Status: Approved* :tada: 

Hi @Miliyonayalew, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Working live demo link. :heavy_check_mark: 

![](https://camo.githubusercontent.com/933d15a5d5acd62a4c99c1e2b391cacfbfe61154e349c4af39c9a99d8d10caab/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3236444f6f4477644e474b416736554b492f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
